service: SlackReplyBot
provider:
  name: aws
  runtime: python3.6
  stage:  ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./enviroment_dev.yml)}
      prd: ${file(./enviroment_prd.yml)}
functions:
  fnc:
    handler: main.handler
    events:
      - http:
          path: /
          method: POST
    environment:
      ${self:custom.otherfile.environment.${self:provider.stage}}
